name: build chromium

on:
  push:

jobs:
  build-chromium:
    runs-on: ubuntu-latest
    steps:
      - run: df -h
      - name: free up space
        run: |
          sudo rm -rf /usr/local/lib/android # ~14G
          sudo rm -rf /usr/share/dotnet # ~2.8G
          sudo rm -rf /usr/local/.ghcup # ~2.3G
          sudo rm -rf /usr/share/swift # ~1.6G
          sudo rm -rf /usr/lib/{jvm,google-cloud-sdk,mono} # ~3G
          sudo rm -rf /usr/local/lib/node_modules # ~1G
          sudo rm -rf /usr/local/graalvm # ~1G
          sudo rm -rf /opt/hostedtoolcache/* # ~6G
          sudo rm -rf /opt/az # ~1.2G
          docker system prune -af --volumes # ~4.3G
      - run: df -h

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: zaubernerd
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: docker pull zaubernerd/chromium-builder:latest
      - run: df -h

      - name: start docker container
        id: start-container
        run: |
          ID="$(docker run -d zaubernerd/chromium-builder:latest tail -f /dev/null)"
          echo "::set-output name=id::${ID}"

      - run: docker exec ${{ steps.start-container.outputs.id }} git checkout -- build/install-build-deps.sh
      - run: docker exec ${{ steps.start-container.outputs.id }} git rebase-update
      - run: df -h

      - run: docker exec ${{ steps.start-container.outputs.id }} gclient sync
      - run: df -h

      - run: docker exec ${{ steps.start-container.outputs.id }} sed -i 's/package_exists snapcraft/package_exists snapcraftdoesnotworkindocker/' ./build/install-build-deps.sh
      - run: docker exec ${{ steps.start-container.outputs.id }} ./build/install-build-deps.sh
      - run: df -h

      - run: docker exec ${{ steps.start-container.outputs.id }} gclient runhooks
      - run: df -h

      - run: docker exec ${{ steps.start-container.outputs.id }} autoninja -C out/Default chrome
      - run: docker exec ${{ steps.start-container.outputs.id }} autoninja -C out/Default chrome/installer/linux:stable_deb
      - run: df -h

      - name: Setup tmate session
        if: failure()
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
