name: icecc cluster

on:
  push:

jobs:
  icecc-cluster:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        type: [scheduler, node0, node1, node2, node3, node4, node5, node6, node7, node8, node9]
    steps:
      - uses: actions/checkout@v3

      - name: set hostname to ${{ matrix.type }}
        run: sudo hostnamectl set-hostname ${{ matrix.type }}

      - name: setup tailscale
        uses: ./.github/actions/tailscale-action
        with:
          tailscale-auth-key: ${{ secrets.tailscale_key }}
          tailscale-api-key: ${{ secrets.tailscale_api_key }}
          tailscale-network-name: ${{ secrets.tailscale_network_name }}

      - name: setup icecc
        uses: ./.github/actions/icecc-action
        with:
          scheduler-host: scheduler
          is-scheduler: ${{ matrix.type == 'scheduler' }}
          is-node: ${{ matrix.type != 'scheduler' }}
      
      - run: sleep 6h
