name: Test Pull Request events

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo $GITHUB_BASE_REF
          echo $GITHUB_HEAD_REF
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
          echo $GITHUB_REF_TYPE
          echo $GITHUB_SHA
      - run: git ls-remote
      - run: echo merge_commit_sha ${{ github.event.pull_request.merge_commit_sha }}
      - run: git fetch +merge:refs/pull/${{ github.event.pull_request.number }}/merge
