name: artifacts tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p top-level-folder/sub-folder
      - run: echo "hello" > top-level-folder/hello.txt
      - run: echo "world" > top-level-folder/sub-folder/world.txt
      - uses: actions/upload-artifact@v3
        with:
          name: "my-folder"
          path: "top-level-folder"
      - run: rm -rf top-level-folder
      - uses: actions/download-artifact@v3
        with:
          name: "my-folder"
      - run: ls -R
