name: push

on: push

jobs:
  job-1:
    name: "job-1"
    runs-on: ubuntu-latest
    steps:
      - run: which node-gyp || true
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
      - run: which node-gyp || true
