name: push

on: push

jobs:
  job-1:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - version: "20.04"
            release: "focal"
          - version: "22.04"
            release: "jammy"
        arch:
          - amd64
          - arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - run: |
          echo "arch: ${{ matrix.arch }}, version: ${{ matrix.version.version }}, release: ${{ matrix.version.release }}"
