name: push

on: push

jobs:
  ubuntu-latest:
    runs-on: ubuntu-latest
    steps:
      - run: node --version

  ubuntu-22:
    runs-on: ubuntu-22.04
    steps:
      - run: node --version

  ubuntu-20:
    runs-on: ubuntu-22.04
    steps:
      - run: node --version
