name: push

on:
  push:

jobs:
  job-1:
    runs-on: ubuntu-latest
    services:
      redis:
        image: "redis:${{ 'latest' }}"
        env:
          REDIS_PASSWORD: "${{ 'password' }}"
        ports:
          - "6379:${{ '6379' }}"
        volumes:
          - "redis:${{ '/data' }}"
        options: --add-host ${{ 'host.docker.internal' }}:host-gateway
    steps:
      - run: echo "Hello, world!"
