name: test services

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      IMAGE_NAME: "${{ env.IMAGE_NAME }}"
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: set lowercase tag
        run: echo "IMAGE_NAME=ghcr.io/${GITHUB_REPOSITORY,,}:latest" >>${GITHUB_ENV}
      - uses: docker/build-push-action@v4
        id: build
        with:
          context: .
          push: true
          tags: "${{ env.IMAGE_NAME }}"

  test-linux-container:
    runs-on: ubuntu-latest
    needs: build
    container: "${{ needs.build.outputs.IMAGE_NAME }}"
    services:
      nginx:
        image: "nginx:latest"
      other:
        image: "${{ needs.build.outputs.IMAGE_NAME }}"
    steps:
      - run: sudo apt-get -qq update && sudo apt-get -yqq install curl
      - run: curl -s http://nginx > /dev/null

  test-linux-host:
    runs-on: ubuntu-latest
    needs: build
    services:
      nginx:
        image: "nginx:latest"
        ports:
          - "80:80"
      other:
        image: "${{ needs.build.outputs.IMAGE_NAME }}"
    steps:
      - run: sudo apt-get -qq update && sudo apt-get -yqq install curl
      - run: curl -s http://localhost > /dev/null
