name: push

on:
  push:

jobs:
  job-1:
    runs-on: ubuntu-latest
    container: 
      image: "ubuntu:latest"
    services:
      nginx:
        image: "nginx:latest"
        ports:
          - "80:80"
    steps:
      - run: curl -v http://nginx
