name: Failing workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Action Test
    container:
      image: ubuntu:22.04
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
    steps:
      - run: apt-get update -qq && apt-get -yqq install docker.io
      - uses: ZauberNerd/sauce-connect-action@tool-cache
        with:
          username: ${{ secrets.SAUCE_USERNAME }}
          accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
          tunnelName: github-action-tunnel
          region: eu-central
      - run: hostname -f
      - run: node -e "require('http').createServer((req, res) => { res.end('works') }).listen(8080)"
