name: Test Pull Request events

on:
  schedule:
    - cron: "0/5 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_EVENT_PATH
      - run: cat $GITHUB_EVENT_PATH
