name: CI

on:
  pull_request:
    types:
      - labeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "pull_request.labeled with an open PR"
      - run: env
