name: CI on-test-456

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $GITHUB_SHA
      - run: echo $GITHUB_REF
      - run: echo $CONTEXT
        env:
          context: ${{ toJSON(github.event) }}
