name: CI

on:
  workflow_dispatch:
  pull_request:
    types:
      - labeled
      - unlabeled

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "pull_request.labeled - workflow changed on master"
      - run: env
