name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: env

  setup:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - run: echo "setup"

  test:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: echo "test"
      - run: exit 1

  teardown:
    runs-on: ubuntu-latest
    needs: [test]
    if: ${{ always() }}
    steps:
      - run: echo "teardown"

  run-if-build:
    runs-on: ubuntu-latest
    needs: [test]
    if: failure()
    steps:
      - run: echo "run-if-build"

  after-teardown:
    runs-on: ubuntu-latest
    needs: [teardown]
    steps:
      - run: echo "after teardown"

  after-test:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: echo "after test"
