name: Workflow A

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ok"
      - run: |
          gh workflow run workflow-b.yml --ref="${{ github.ref }}"

  container-test:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - run: which gh || true
      - run: mount
